platform :ios, '9.0'

target 'my-music-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my-music-app
    
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'Kingfisher'
    
end

